#!/usr/bin/env bash
# vim: ft=sh
set -e

if [ -f config/task.env ]; then
  source config/task.env
fi

dev () {
  cd config
  source dev.env
  cd -
  clj "$@" -A:girouette:test -M -m hub.core
}

css () {
  clj -X:girouette
}

generate-keys () {
  clj -X hub.admin/generate-keys
}

tests () {
  clj -X:test
}

build () {
  tests
  clj -X:girouette :watch? false
  clj -X:uberjar
}

logs () {
  ssh root@$TASK_HOST journalctl -u app -f -n 300
}

deploy () {
  # todo hard code TASK_USER
  scp config/prod.env $TASK_USER@$TASK_HOST:config.env
  time git push prod master
}

prod-repl () {
  echo Connect to nrepl port 7888
  ssh -NL 7888:localhost:7888 root@$TASK_HOST
}

"$@"
