(ns hub.extra.curate.words)

(def all-colors
  ["bg-gray-50" "bg-gray-100" "bg-gray-200" "bg-gray-300" "bg-gray-400"
   "bg-gray-500" "bg-gray-600" "bg-gray-700" "bg-gray-800" "bg-gray-900"
   "bg-red-50" "bg-red-100" "bg-red-200" "bg-red-300" "bg-red-400"
   "bg-red-500" "bg-red-600" "bg-red-700" "bg-red-800" "bg-red-900"
   "bg-yellow-50" "bg-yellow-100" "bg-yellow-200" "bg-yellow-300" "bg-yellow-400"
   "bg-yellow-500" "bg-yellow-600" "bg-yellow-700" "bg-yellow-800" "bg-yellow-900"
   "bg-green-50" "bg-green-100" "bg-green-200" "bg-green-300" "bg-green-400"
   "bg-green-500" "bg-green-600" "bg-green-700" "bg-green-800" "bg-green-900"
   "bg-blue-50" "bg-blue-100" "bg-blue-200" "bg-blue-300" "bg-blue-400"
   "bg-blue-500" "bg-blue-600" "bg-blue-700" "bg-blue-800" "bg-blue-900"
   "bg-indigo-50" "bg-indigo-100" "bg-indigo-200" "bg-indigo-300" "bg-indigo-400"
   "bg-indigo-500" "bg-indigo-600" "bg-indigo-700" "bg-indigo-800" "bg-indigo-900"
   "bg-purple-50" "bg-purple-100" "bg-purple-200" "bg-purple-300" "bg-purple-400"
   "bg-purple-500" "bg-purple-600" "bg-purple-700" "bg-purple-800" "bg-purple-900"
   "bg-pink-50" "bg-pink-100" "bg-pink-200" "bg-pink-300" "bg-pink-400"
   "bg-pink-500" "bg-pink-600" "bg-pink-700" "bg-pink-800" "bg-pink-90"])

(def adjectives
  ["adorable"
   "adventurous"
   "aggressive"
   "agreeable"
   "alert"
   "alive"
   "amused"
   "angry"
   "annoyed"
   "annoying"
   "anxious"
   "arrogant"
   "ashamed"
   "attractive"
   "average"
   "awful"
   "bad"
   "beautiful"
   "better"
   "bewildered"
   "black"
   "bloody"
   "blue"
   "blue-eyed"
   "blushing"
   "bored"
   "brainy"
   "brave"
   "breakable"
   "bright"
   "busy"
   "calm"
   "careful"
   "cautious"
   "charming"
   "cheerful"
   "clean"
   "clear"
   "clever"
   "cloudy"
   "clumsy"
   "colorful"
   "combative"
   "comfortable"
   "concerned"
   "condemned"
   "confused"
   "cooperative"
   "courageous"
   "crazy"
   "creepy"
   "crowded"
   "cruel"
   "curious"
   "cute"
   "dangerous"
   "dark"
   "dead"
   "defeated"
   "defiant"
   "delightful"
   "depressed"
   "determined"
   "different"
   "difficult"
   "disgusted"
   "distinct"
   "disturbed"
   "dizzy"
   "doubtful"
   "drab"
   "dull"
   "eager"
   "easy"
   "elated"
   "elegant"
   "embarrassed"
   "enchanting"
   "encouraging"
   "energetic"
   "enthusiastic"
   "envious"
   "evil"
   "excited"
   "expensive"
   "exuberant"
   "fair"
   "faithful"
   "famous"
   "fancy"
   "fantastic"
   "fierce"
   "filthy"
   "fine"
   "foolish"
   "fragile"
   "frail"
   "frantic"
   "friendly"
   "frightened"
   "funny"
   "gentle"
   "gifted"
   "glamorous"
   "gleaming"
   "glorious"
   "good"
   "gorgeous"
   "graceful"
   "grieving"
   "grotesque"
   "grumpy"
   "handsome"
   "happy"
   "healthy"
   "helpful"
   "helpless"
   "hilarious"
   "homeless"
   "homely"
   "horrible"
   "hungry"
   "hurt"
   "ill"
   "important"
   "impossible"
   "inexpensive"
   "innocent"
   "inquisitive"
   "itchy"
   "jealous"
   "jittery"
   "jolly"
   "joyous"
   "kind"
   "lazy"
   "light"
   "lively"
   "lonely"
   "long"
   "lovely"
   "lucky"
   "magnificent"
   "misty"
   "modern"
   "motionless"
   "muddy"
   "mushy"
   "mysterious"
   "nasty"
   "naughty"
   "nervous"
   "nice"
   "nutty"
   "obedient"
   "obnoxious"
   "odd"
   "old-fashioned"
   "open"
   "outrageous"
   "outstanding"
   "panicky"
   "perfect"
   "plain"
   "pleasant"
   "poised"
   "poor"
   "powerful"
   "precious"
   "prickly"
   "proud"
   "putrid"
   "puzzled"
   "quaint"
   "real"
   "relieved"
   "repulsive"
   "rich"
   "scary"
   "selfish"
   "shiny"
   "shy"
   "silly"
   "sleepy"
   "smiling"
   "smoggy"
   "sore"
   "sparkling"
   "splendid"
   "spotless"
   "stormy"
   "strange"
   "stupid"
   "successful"
   "super"
   "talented"
   "tame"
   "tasty"
   "tender"
   "tense"
   "terrible"
   "thankful"
   "thoughtful"
   "thoughtless"
   "tired"
   "tough"
   "troubled"
   "ugliest"
   "ugly"
   "uninterested"
   "unsightly"
   "unusual"
   "upset"
   "uptight"
   "vast"
   "victorious"
   "vivacious"
   "wandering"
   "weary"
   "wicked"
   "wide-eyed"
   "wild"
   "witty"
   "worried"
   "worrisome"
   "wrong"
   "zany"
   "zealous"])

(def animals
  ["Aardvark"
   "Abyssinian"
   "Adelie Penguin"
   "Affenpinscher"
   "Afghan Hound"
   "African Bullfrog"
   "African Bush Elephant"
   "African Civet"
   "African Clawed Frog"
   "African Forest Elephant"
   "African Palm Civet"
   "African Penguin"
   "African Tree Toad"
   "African Wild Dog"
   "Ainu"
   "Airedale Terrier"
   "Airedoodle"
   "Akbash"
   "Akita"
   "Alaskan Malamute"
   "Albacore Tuna"
   "Albatross"
   "Aldabra Giant Tortoise"
   "Alligator"
   "Alligator Gar"
   "Alpaca"
   "Alpine Dachsbracke"
   "Amazon River Dolphin (Pink Dolphin)"
   "American Alsatian"
   "American Bulldog"
   "American Cocker Spaniel"
   "American Coonhound"
   "American Eskimo Dog"
   "American Foxhound"
   "American Hairless Terrier"
   "American Pit Bull Terrier"
   "American Staffordshire Terrier"
   "American Water Spaniel"
   "Amur Leopard"
   "Anatolian Shepherd Dog"
   "Anchovies"
   "Angelfish"
   "Ant"
   "Anteater"
   "Antelope"
   "Appenzeller Dog"
   "Arapaima"
   "Arctic Fox"
   "Arctic Hare"
   "Arctic Wolf"
   "Armadillo"
   "Asian Elephant"
   "Asian Giant Hornet"
   "Asian Palm Civet"
   "Asiatic Black Bear"
   "Aurochs"
   "Aussiedoodle"
   "Aussiedor"
   "Australian Cattle Dog"
   "Australian Kelpie Dog"
   "Australian Labradoodle"
   "Australian Mist"
   "Australian Shepherd"
   "Australian Terrier"
   "Avocet"
   "Axolotl"
   "Aye Aye"
   "Baboon"
   "Bactrian Camel"
   "Badger"
   "Baiji"
   "Balinese"
   "Banded Palm Civet"
   "Bandicoot"
   "Banjo Catfish"
   "Barb"
   "Barn Owl"
   "Barnacle"
   "Barracuda"
   "Barramundi Fish"
   "Basenji Dog"
   "Basking Shark"
   "Bassador"
   "Basset Fauve de Bretagne"
   "Basset Hound"
   "Bassetoodle"
   "Bat"
   "Bavarian Mountain Hound"
   "Beagador"
   "Beagle"
   "Bear"
   "Bearded Collie"
   "Bearded Dragon"
   "Beaver"
   "Bedlington Terrier"
   "Beetle"
   "Beluga Sturgeon"
   "Bengal Tiger"
   "Bernedoodle"
   "Bernese Mountain Dog"
   "Bichir"
   "Bichon Frise"
   "Biewer Terrier"
   "Binturong"
   "Bird"
   "Birds Of Paradise"
   "Birman"
   "Bison"
   "Black Marlin"
   "Black Rhinoceros"
   "Black Russian Terrier"
   "Black Widow Spider"
   "Blobfish"
   "Bloodhound"
   "Blue Jay"
   "Blue Lacy Dog"
   "Blue Whale"
   "Bluefin Tuna"
   "Bluetick Coonhound"
   "Bobcat"
   "Boglen Terrier"
   "Bolognese Dog"
   "Bombay"
   "Bongo"
   "Bonito Fish"
   "Bonobo"
   "Booby"
   "Borador"
   "Border Collie"
   "Border Terrier"
   "Bordoodle"
   "Bornean Orang-utan"
   "Borneo Elephant"
   "Boston Terrier"
   "Bottlenose Dolphin"
   "Bowfin"
   "Bowhead Whale"
   "Boxador"
   "Boxer Dog"
   "Boxerdoodle"
   "Boykin Spaniel"
   "Brazilian Terrier"
   "British Timber"
   "Brown Bear"
   "Budgerigar"
   "Buffalo"
   "Bull Shark"
   "Bull Terrier"
   "Bulldog"
   "Bullfrog"
   "Bullmastiff"
   "Bumblebee"
   "Burmese"
   "Burrowing Frog"
   "Butterfly"
   "Butterfly Fish"
   "Caiman"
   "Caiman Lizard"
   "Cairn Terrier"
   "Camel"
   "Camel Spider"
   "Canaan Dog"
   "Canadian Eskimo Dog"
   "Capybara"
   "Caracal"
   "Carolina Dog"
   "Carp"
   "Cassowary"
   "Cat"
   "Caterpillar"
   "Catfish"
   "Cavador"
   "Cavalier King Charles Spaniel"
   "Cavapoo"
   "Centipede"
   "Cesky Fousek"
   "Cesky Terrier"
   "Chameleon"
   "Chamois"
   "Cheetah"
   "Chesapeake Bay Retriever"
   "Chicken"
   "Chihuahua"
   "Chimaera"
   "Chimpanzee"
   "Chinchilla"
   "Chinese Crested Dog"
   "Chinese Paddlefish"
   "Chinook"
   "Chinstrap Penguin"
   "Chipmunk"
   "Chipoo"
   "Chow Chow"
   "Cichlid"
   "Clouded Leopard"
   "Clownfish"
   "Clumber Spaniel"
   "Coati"
   "Cockapoo"
   "Cockatoo"
   "Cockroach"
   "Codfish"
   "Coelacanth"
   "Collared Peccary"
   "Collie"
   "Colossal Squid"
   "Common Buzzard"
   "Common Frog"
   "Common Loon"
   "Common Toad"
   "Cooper’s Hawk"
   "Coral"
   "Corgidor"
   "Corgipoo"
   "Cotton-top Tamarin"
   "Cougar"
   "Cow"
   "Coyote"
   "Crab"
   "Crab-Eating Macaque"
   "Crane"
   "Crested Penguin"
   "Crocodile"
   "Cross River Gorilla"
   "Curly Coated Retriever"
   "Cuscus"
   "Cuttlefish"
   "Dachsador"
   "Dachshund"
   "Dalmadoodle"
   "Dalmador"
   "Dalmatian"
   "Darwin’s Frog"
   "Deer"
   "Desert Locust"
   "Desert Rain Frog"
   "Desert Tortoise"
   "Deutsche Bracke"
   "Dhole"
   "Dingo"
   "Discus"
   "Doberman Pinscher"
   "Dodo"
   "Dog"
   "Dogo Argentino"
   "Dogue De Bordeaux"
   "Dolphin"
   "Donkey"
   "Dormouse"
   "Double Doodle"
   "Doxiepoo"
   "Dragonfish"
   "Dragonfly"
   "Drever"
   "Drum Fish"
   "Duck"
   "Dugong"
   "Dunker"
   "Dusky Dolphin"
   "Dwarf Crocodile"
   "Eagle"
   "Earwig"
   "Eastern Gorilla"
   "Eastern Lowland Gorilla"
   "Echidna"
   "Edible Frog"
   "Eel"
   "Egyptian Mau"
   "Electric Eel"
   "Elephant"
   "Elephant Seal"
   "Elephant Shrew"
   "Emperor Penguin"
   "Emperor Tamarin"
   "Emu"
   "English Cocker Spaniel"
   "English Shepherd"
   "English Springer Spaniel"
   "Entlebucher Mountain Dog"
   "Epagneul Pont Audemer"
   "Ermine"
   "Eskimo Dog"
   "Eskipoo"
   "Estrela Mountain Dog"
   "Falcon"
   "False Killer Whale"
   "Fangtooth"
   "Fennec Fox"
   "Ferret"
   "Field Spaniel"
   "Fin Whale"
   "Finnish Spitz"
   "Fire-Bellied Toad"
   "Fish"
   "Fishing Cat"
   "Flamingo"
   "Flat-Coated Retriever"
   "Florida Gar"
   "Flounder"
   "Fluke Fish (summer flounder)"
   "Fly"
   "Flying Squirrel"
   "Fossa"
   "Fox"
   "Fox Terrier"
   "French Bulldog"
   "Frigatebird"
   "Frilled Lizard"
   "Frilled Shark"
   "Frog"
   "Fur Seal"
   "Galapagos Penguin"
   "Galapagos Tortoise"
   "Gar"
   "Gecko"
   "Gentoo Penguin"
   "Geoffroys Tamarin"
   "Gerbil"
   "German Pinscher"
   "German Shepherd Guide"
   "German Sheprador"
   "Gharial"
   "Giant African Land Snail"
   "Giant Clam"
   "Giant Panda Bear"
   "Giant Schnauzer"
   "Giant Schnoodle"
   "Gibbon"
   "Gila Monster"
   "Giraffe"
   "Glass Frog"
   "Glass Lizard"
   "Glen Of Imaal Terrier"
   "Glow Worm"
   "Goat"
   "Goblin Shark"
   "Goldador"
   "Golden Lion Tamarin"
   "Golden Masked Owl"
   "Golden Oriole"
   "Golden Retriever"
   "Golden-Crowned Flying Fox"
   "Goldendoodle"
   "Goliath Frog"
   "Goose"
   "Gopher"
   "Gorilla"
   "Gouldian Finch"
   "Grasshopper"
   "Gray Tree Frog"
   "Great Dane"
   "Great Danoodle"
   "Great Pyrenees"
   "Great White Shark"
   "Greater Swiss Mountain Dog"
   "Green Anole"
   "Green Bee-Eater"
   "Green Frog"
   "Green Tree Frog"
   "Greenland Dog"
   "Grey Mouse Lemur"
   "Grey Reef Shark"
   "Grey Seal"
   "Greyhound"
   "Grizzly Bear"
   "Grouse"
   "Guinea Fowl"
   "Guinea Pig"
   "Guppy"
   "Hagfish"
   "Hammerhead Shark"
   "Hamster"
   "Hare"
   "Harpy Eagle"
   "Harrier"
   "Havanese"
   "Havapoo"
   "Hawaiian Crow"
   "Hedgehog"
   "Hercules Beetle"
   "Hermit Crab"
   "Heron"
   "Herring"
   "Highland Cattle"
   "Himalayan"
   "Hippopotamus"
   "Honduran White Bat"
   "Honey Badger"
   "Honey Bee"
   "Hoopoe"
   "Horn Shark"
   "Hornbill"
   "Horned Frog"
   "Horse"
   "Horseshoe Crab"
   "House Finch"
   "Howler Monkey"
   "Human"
   "Humboldt Penguin"
   "Hummingbird"
   "Humpback Whale"
   "Huskador"
   "Huskydoodle"
   "Hyena"
   "Ibis"
   "Ibizan Hound"
   "Iguana"
   "Immortal Jellyfish"
   "Impala"
   "Indian Elephant"
   "Indian Palm Squirrel"
   "Indian Rhinoceros"
   "Indian Star Tortoise"
   "Indochinese Tiger"
   "Indri"
   "Insects"
   "Irish Doodle"
   "Irish Setter"
   "Irish Terrier"
   "Irish WolfHound"
   "Italian Greyhound"
   "Jack Russell"
   "Jackal"
   "Jaguar"
   "Japanese Chin"
   "Japanese Macaque"
   "Japanese Terrier"
   "Javan Rhinoceros"
   "Javanese"
   "Jellyfish"
   "Jerboa"
   "Kakapo"
   "Kangaroo"
   "Keel-Billed Toucan"
   "Keeshond"
   "Kerry Blue Terrier"
   "Killer Whale"
   "King Cobra"
   "King Crab"
   "King Penguin"
   "Kingfisher"
   "Kinkajou"
   "Kiwi"
   "Koala"
   "Komodo Dragon"
   "Krill"
   "Kudu"
   "Labmaraner"
   "Labradane"
   "Labradoodle"
   "Labrador Retriever"
   "Labraheeler"
   "Ladybug"
   "Lakeland Terrier"
   "Lamprey"
   "Leaf-Tailed Gecko"
   "Lemming"
   "Lemur"
   "Leopard"
   "Leopard Cat"
   "Leopard Frog"
   "Leopard Seal"
   "Leopard Tortoise"
   "Lhasapoo"
   "Liger"
   "Lion"
   "Lionfish"
   "Little Penguin"
   "Lizard"
   "Llama"
   "Loach"
   "Lobster"
   "Long-Eared Owl"
   "Longnose Gar"
   "Lungfish"
   "Lynx"
   "Macaroni Penguin"
   "Macaw"
   "Magellanic Penguin"
   "Magpie"
   "Maine Coon"
   "Malayan Civet"
   "Malayan Tiger"
   "Maltese"
   "Maltipoo"
   "Manatee"
   "Manchester Terrier"
   "Mandrill"
   "Maned Wolf"
   "Manta Ray"
   "Marine Toad"
   "Markhor"
   "Marmot"
   "Marsh Frog"
   "Masked Palm Civet"
   "Mastador"
   "Mastiff"
   "Mayfly"
   "Meerkat"
   "Megalodon"
   "Mexican Free-Tailed Bat"
   "Milkfish"
   "Millipede"
   "Mini Labradoodle"
   "Miniature Bull Terrier"
   "Mink"
   "Minke Whale"
   "Mole"
   "Molly"
   "Monarch Butterfly"
   "Mongoose"
   "Mongrel"
   "Monitor Lizard"
   "Monkey"
   "Monkfish"
   "Monte Iberia Eleuth"
   "Moorhen"
   "Moose"
   "Moray Eel"
   "Moth"
   "Mountain Gorilla"
   "Mountain Lion"
   "Mourning Dove"
   "Mouse"
   "Mule"
   "Muskox"
   "Muskrat"
   "Narwhal"
   "Neanderthal"
   "Neapolitan Mastiff"
   "Newfoundland"
   "Newfypoo"
   "Newt"
   "Nightingale"
   "Norfolk Terrier"
   "North American Black Bear"
   "Northern Inuit Dog"
   "Norwegian Forest"
   "Norwich Terrier"
   "Numbat"
   "Nurse Shark"
   "Ocelot"
   "Octopus"
   "Okapi"
   "Old English Sheepdog"
   "Olm"
   "Opossum"
   "Orang-utan"
   "Ostrich"
   "Otter"
   "Oyster"
   "Paddlefish"
   "Pademelon"
   "Pangolin"
   "Panther"
   "Parrot"
   "Parson Russell Terrier"
   "Patas Monkey"
   "Patterdale Terrier"
   "Peacock"
   "Peekapoo"
   "Pekingese"
   "Pelican"
   "Penguin"
   "Pere Davids Deer"
   "Peregrine Falcon"
   "Persian"
   "Petit Basset Griffon Vendéen"
   "Pheasant"
   "Pied Tamarin"
   "Pig"
   "Pigeon"
   "Pika"
   "Pike Fish"
   "Pileated Woodpecker"
   "Pink Fairy Armadillo"
   "Piranha"
   "Pitador"
   "Platypus"
   "Pointer"
   "Poison Dart Frog"
   "Polar Bear"
   "Pomapoo"
   "Pomeranian"
   "Pond Skater"
   "Poochon"
   "Poodle"
   "Poogle"
   "Pool Frog"
   "Porcupine"
   "Porpoise"
   "Possum"
   "Prawn"
   "Proboscis Monkey"
   "Pufferfish"
   "Puffin"
   "Pug"
   "Pugapoo"
   "Puma"
   "Purple Emperor Butterfly"
   "Purple Finch"
   "Puss Moth"
   "Pygmy Hippopotamus"
   "Pygmy Marmoset"
   "Pyrador"
   "Pyredoodle"
   "Quail"
   "Quetzal"
   "Quokka"
   "Quoll"
   "Rabbit"
   "Raccoon"
   "Raccoon Dog"
   "Radiated Tortoise"
   "Ragdoll"
   "Rat"
   "Rat Terrier"
   "Rattlesnake"
   "Red Finch"
   "Red Fox"
   "Red Knee Tarantula"
   "Red Panda"
   "Red Wolf"
   "Red-handed Tamarin"
   "Reindeer"
   "Rhinoceros"
   "River Turtle"
   "Robin"
   "Rock Hyrax"
   "Rockfish"
   "Rockhopper Penguin"
   "Roseate Spoonbill"
   "Rottweiler"
   "Royal Penguin"
   "Russell Terrier"
   "Russian Blue"
   "Saarloos Wolfdog"
   "Saber-Toothed Tiger"
   "Sable"
   "Saiga"
   "Saint Berdoodle"
   "Saint Bernard"
   "Salamander"
   "Salmon"
   "Samoyed"
   "Sand Lizard"
   "Saola"
   "Sardines"
   "Sawfish"
   "Schnoodle"
   "Scimitar-horned Oryx"
   "Scorpion"
   "Scorpion Fish"
   "Scottish Terrier"
   "Sea Dragon"
   "Sea Lion"
   "Sea Otter"
   "Sea Slug"
   "Sea Squirt"
   "Sea Turtle"
   "Sea Urchin"
   "Seahorse"
   "Seal"
   "Sealyham Terrier"
   "Serval"
   "Shark"
   "Sheep"
   "Sheepadoodle"
   "Shepadoodle"
   "Shiba Inu"
   "Shih Poo"
   "Shih Tzu"
   "Shrimp"
   "Siamese"
   "Siamese Fighting Fish"
   "Siberian"
   "Siberian Husky"
   "Siberian Tiger"
   "Siberpoo"
   "Silky Terrier"
   "Silver Dollar"
   "Skate Fish"
   "Skipjack Tuna"
   "Skunk"
   "Skye Terrier"
   "Sloth"
   "Slow Worm"
   "Smooth Fox Terrier"
   "Snail"
   "Snake"
   "Snapping Turtle"
   "Snowshoe"
   "Snowshoe Hare"
   "Snowy Owl"
   "Somali"
   "South China Tiger"
   "Spadefoot Toad"
   "Spanador"
   "Sparrow"
   "Spectacled Bear"
   "Sperm Whale"
   "Spider Monkey"
   "Spiny Dogfish"
   "Spixs Macaw"
   "Sponge"
   "Spotted Gar"
   "Springador"
   "Springerdoodle"
   "Squid"
   "Squirrel"
   "Squirrel Monkey"
   "Sri Lankan Elephant"
   "Staffordshire Bull Terrier"
   "Stag Beetle"
   "Starfish"
   "Steller’s Sea Cow"
   "Stick Insect"
   "Stingray"
   "Stoat"
   "Striped Rocket Frog"
   "Sturgeon"
   "Sucker Fish"
   "Sugar Glider"
   "Sumatran Elephant"
   "Sumatran Orang-utan"
   "Sumatran Rhinoceros"
   "Sumatran Tiger"
   "Sun Bear"
   "Swai Fish"
   "Swan"
   "Swedish Vallhund"
   "Taco Terrier"
   "Tamaskan"
   "Tang"
   "Tapanuli Orang-utan"
   "Tapir"
   "Tarpon"
   "Tarsier"
   "Tasmanian Devil"
   "Tawny Owl"
   "Teddy Roosevelt Terrier"
   "Tenterfield Terrier"
   "Termite"
   "Terrier"
   "Tetra"
   "Thorny Devil"
   "Tibetan Mastiff"
   "Tibetan Terrier"
   "Tiffany"
   "Tiger"
   "Tiger Salamander"
   "Tiger Shark"
   "Toadfish"
   "Tortoise"
   "Toucan"
   "Toy Fox Terrier"
   "Toy Poodle"
   "Tree Frog"
   "Tropicbird"
   "Tuatara"
   "Tuna"
   "Turkey"
   "Turkish Angora"
   "Uakari"
   "Uguisu"
   "Umbrellabird"
   "Utonagan"
   "Vampire Bat"
   "Vampire Squid"
   "Vaquita"
   "Vervet Monkey"
   "Vulture"
   "Wallaby"
   "Walleye Fish"
   "Walrus"
   "Wandering Albatross"
   "Warthog"
   "Wasp"
   "Water Buffalo"
   "Water Dragon"
   "Water Vole"
   "Weasel"
   "Weimardoodle"
   "Welsh Corgi"
   "Welsh Terrier"
   "West Highland Terrier"
   "Western Gorilla"
   "Western Lowland Gorilla"
   "Westiepoo"
   "Whale Shark"
   "Wheaten Terrier"
   "Whippet"
   "White Rhinoceros"
   "White Tiger"
   "White-Faced Capuchin"
   "Whoodle"
   "Whooping Crane"
   "Wild Boar"
   "Wildebeest"
   "Wire Fox Terrier"
   "Wolf"
   "Wolf Eel"
   "Wolf Spider"
   "Wolffish"
   "Wolverine"
   "Wombat"
   "Wood Frog"
   "Woodlouse"
   "Woodpecker"
   "Woolly Mammoth"
   "Woolly Monkey"
   "Wrasse"
   "Wyoming Toad"
   "X-Ray Tetra"
   "Xerus"
   "Yak"
   "Yellow-Eyed Penguin"
   "Yellowfin Tuna"
   "Yorkie Poo"
   "Yorkshire Terrier"
   "Zebra"
   "Zebra Shark"
   "Zebu"
   "Zonkey"
   "Zorse"])
